<?php
/**
 * 功能描述:
 *  自定义事件
 * @author zhangjun <zhangjun1@yy.com>
 * @version 1.0
 * Date: 2016/7/14 18:23
 */
 namespace frontend\components;

 use yii\base\Component;

 class MyEvent extends Component{

        //自定义事件
        const EVENT_HELLO = 0;
        const EVENT_SEND = 1;

      public function bar()
      {
        $this->trigger(self::EVENT_HELLO);
      }

      public function init()
      {
         parent::init(); // TODO: Change the autogenerated stub
         $this->on(self::EVENT_HELLO, function($event){
             echo "注册事件处理";
         }
         );
  }

 }

